# index alias
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# API proxy
[[redirects]]
  from = "/api/*"
  to = "https://jarg-be.fly.dev/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"

# 86400 = 1d
# 604800 = 7d

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=86400,
    must-revalidate
    '''

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    cache-control = '''
    max-age=86400,
    must-revalidate
    '''