springdoc:
  api-docs:
    path: /v3/api-docs

logging.level:
  org.springframework: info

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'

security:
  cors:
    allowedOrigins: http://localhost:8080, http://localhost:5173
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
    allowCredentials: true
    allowedHeaders:
      - Content-Type
      - Access-Control-Request-Method
      - Access-Control-Allow-Credentials
      - Access-Control-Allow-Origin
      - Access-Control-Allow-Headers
      - x-requested-with
      - Authorization
      - origin
      - accept
  auth:
    jwt:
      cookie:
        domain:
      publicKey: ${APP_JWT_PUBLIC_KEY}
      privateKey: ${APP_JWT_PRIVATE_KEY}
metrics:
  skipIfLessThan: 50