springdoc:
  api-docs:
    path: /v3/api-docs

logging.level:
  org.springframework: info

security:
  cors:
    allowedOrigins: http://localhost:8080
    allowedMethods:
      - GET
      - POST
    allowCredentials: true
    allowedHeaders:
      - Content-Type
      - Access-Control-Request-Method
      - Access-Control-Allow-Credentials
      - Access-Control-Allow-Origin
      - Access-Control-Allow-Headers
      - x-requested-with
      - Authorization
      - origin
      - accept
  auth:
    jwt:
      cookie:
        domain:
      publicKey: ${APP_JWT_PUBLIC_KEY}
      privateKey: ${APP_JWT_PRIVATE_KEY}
metrics:
  skipIfLessThan: -1