name: "Maven CD - JaRG-BE"
on:
  push:
    branches: [ main ]

env:
  TIMESTAMP: $(date +%s)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Maven Verify
        run: mvn --batch-mode --update-snapshots -f ./jarg-be/pom.xml verify
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout  -f ./jarg-be/pom.xml)-${{ env.TIMESTAMP }}" >> $GITHUB_ENV
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build
        run: docker build ./jarg-be/ --file ./jarg-be/Dockerfile --tag vitalegi/jarg-be:${{ env.RELEASE_VERSION }}
      - name: Docker push
        run: docker push vitalegi/jarg-be:${{ env.RELEASE_VERSION }}
      - name: Deploy to fly.io
        run: flyctl deploy ./jarg-be/ --image vitalegi/jarg-be:${{ env.RELEASE_VERSION }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}