name: "Maven CI - JaRG-BE"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Maven Verify
        run: mvn --batch-mode --update-snapshots -f ./jarg-be/pom.xml verify
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Get POM Version
        id: pom-version
        uses: CptMokoena/maven-get-version-action@master
        with:
          path: ./jarg-be/
      - name: Docker build
        run: docker build ./jarg-be/ --file ./jarg-be/Dockerfile --tag vitalegi/jarg-be:${{ steps.pom-version.outputs.version }}
      - name: Docker push
        run: docker push --image vitalegi/jarg-be:${{ steps.pom-version.outputs.version }}
