name: "Node.js CI jarg-fe"
on: [push]

defaults:
  run:
    working-directory: ./jarg-fe

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    defaults:
      run:
        working-directory: ./jarg-fe

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./jarg-fe
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:unit
